package com.csumb.cst363;

import java.sql.Date;

/*
 * This class is used to transfer data to/from prescription template pages.
 */
public class Prescription {
	
	private int rxid;  // primary key generated by database.
	// following fields are set when doctor creates a prescription.
	private String drugName;
	private int quantity;
	private int patientSsn;
	private String patientName;
	private int doctorssn;
	private String doctorName;
	// following fields will be null or blank until prescription has been filled.
	private String pharmacyID;    
	private String pharmacyAddress; 
	private String pharmacyPhone;
	private String pharmacyName;
	private Date dateFilled;   
	private Date endDate;
	private String cost;
	
	
	public int getRxid() {
		return rxid;
	}
	public void setRxid(int rxid) {
		this.rxid = rxid;
	}
	public String getDrugName() {
		return drugName;
	}
	public void setDrugName(String drugName) {
		this.drugName = drugName;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public int getPatientSsn() {
		return patientSsn;
	}
	public void setPatientSsn(int patientSsn) {
		this.patientSsn = patientSsn;
	}
	public String getPatientName() {
		return patientName;
	}
	public void setPatientName(String patientName) {
		this.patientName = patientName;
	}
    public int getDoctorssn() {
        return doctorssn;
    }
    public void setDoctorssn(int doctorssn) {
        this.doctorssn = doctorssn;
    }
	public String getDoctorName() {
		return doctorName;
	}
	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}
	public String getPharmacyID() {
		return pharmacyID;
	}
	public void setPharmacyID(String pharmacyID) {
		this.pharmacyID = pharmacyID;
	}
	public String getPharmacyAddress() {
		return pharmacyAddress;
	}
	public void setPharmacyAddress(String pharmacyAddress) {
		this.pharmacyAddress = pharmacyAddress;
	}
	public String getPharmacyPhone() {
		return pharmacyPhone;
	}
	public void setPharmacyPhone(String pharmacyPhone) {
		this.pharmacyPhone = pharmacyPhone;
	}
	public String getPharmacyName() {
		return pharmacyName;
	}
	public void setPharmacyName(String pharmacyName) {
		this.pharmacyName = pharmacyName;
	}
	public Date getDateFilled() {
		return dateFilled;
	}
	public void setDateFilled(Date dateFilled) {
		this.dateFilled = dateFilled;
	}
	public Date getEndDate() {
		return endDate;
	}
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}
	public String getCost() {
		return cost;
	}
	public void setCost(String cost) {
		this.cost = cost;
	}
	
	@Override
	public String toString() {
		return "Prescription [rxid=" + rxid + ", drugName=" + drugName + ", quantity=" + quantity + ", patientSsn="
				+ patientSsn + ", patientName=" + patientName + ", doctorSsn=" + doctorssn + ", doctorName="
				+ doctorName + ", pharmacyID=" + pharmacyID + ", pharmacyAddress=" + pharmacyAddress + ", pharmacyName="
				+ pharmacyName + ", dateFilled=" + dateFilled + ", cost=" + cost + "]";
	}

}
